---

- name: Install EPEL repo.
  shell: yum --enablerepo=extras install epel-release -y

- name: Add repository Gluster7.2
  yum_repository:
    name: Gluster7.2
    description: Gluster7.2
    baseurl: http://mirror.centos.org/centos-7/7.7.1908/storage/x86_64/gluster-7
    gpgcheck: no
    enabled: yes

- name: Add Kubernetes
  yum_repository:
    name: Kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: no
    enabled: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Ensure required packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ yum_packages }}"

- name: modprobe dm_snapshot
  shell: modprobe dm_snapshot

- name: modprobe dm_mirror
  shell: modprobe dm_mirror

- name: modprobe dm_thin_pool
  shell: modprobe dm_thin_pool

- name: Copy dm_thin_pool.conf configuration file
  template:
   src: dm_thin_pool.conf.j2
   dest: /etc/modules-load.d/dm_thin_pool.conf
   mode: 0644

- name: Ensure iptables tooling does not use the nftables backend
  shell: update-alternatives --set iptables /usr/sbin/iptables-legacy

#Prepare Firewalld:

- name: Starting services firewalld
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
  with_items:
      - firewalld

- name: need to pause here, otherwise the firewalld service starting can sometimes cause ssh to fail
  pause:
    seconds: 10

- name: Open up firewall ports
  firewalld:
    permanent: yes
    immediate: yes
    state: enabled
    port: "{{ item }}"
  with_items:
      - 6443/tcp
      - 443/tcp
      - 2379/tcp
      - 2380/tcp
      - 10250/tcp
      - 10251/tcp
      - 10252/tcp
      - 10255/tcp
      - 6783/tcp
      - 30000-32767/tcp
      - 8472/udp
      - 2222/tcp
      - 24007/tcp
      - 24008/tcp
      - 49152-49251/tcp
      - 8080/tcp
      - 179/tcp
      - 4789/udp
      - 5473/tcp
      - 10256/tcp
      - 9099/tcp

- name: net.ipv4.ip_forward=1
  shell: sysctl -w net.ipv4.ip_forward=1
